print("======" "DESAFIO 4" "======")
n1 = input("Digite qualquer valor")
print(type(n1))
print("Seu valor é só número?", n1.isnumeric())
print("Seu valor é só letra?", n1.isalpha())
print("Seu valor é apenas letra maiúscula?", n1.isupper())
print("Seu valor é apenas alphanumérico?", n1.isalnum())
print("Seu valor só tem espaço?", n1.isspace())
print("Seu valor é apenas letras minúsculas? ", n1.islower())
